#define bc(f) add(expr::make_smart_callable(f),#f)
#define bcn(f,n) add(expr::make_smart_callable(f),n)
#define bs(s) use(expr::get_all_functions<s>(),#s)
#define bsn(s,n) use(expr::get_all_functions<s>(),n)
#define bv(v) add(expr::make_smart_callable([val=v](){return val;}),#v)
#define bvn(v,n) add(expr::make_smart_callable([val=v](){return val;}),n)